import Image from "next/image";

export default function Home() {
  return (
    <main className="flex h-screen flex-col items-center p-24">
      <h1 className="text-5xl font-bold text-center lg:text-6xl mb-10">Guacchain.com</h1>
      <Image
          className="relative dark:drop-shadow-[0_0_0.3rem_#ffffff70] dark:invert flex-1"
          src="/guacchain.png"
          alt="Guachchain.com Image generated by Gemini AI"
          width={512}
          height={512}
          priority
        />
    </main>
  );
}
